spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8084

management:
  server:
    port: 8094
  endpoints:
    web:
      exposure:
        include: health,info