spring:
  application:
    name: scoring-service
  datasource:
    url: jdbc:postgresql://localhost:5433/scoring_db
    username: riskmesh
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8082

management:
  server:
    port: 8092
  endpoints:
    web:
      exposure:
        include: health,info