services:
  postgres-ingestion:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ingestion_db
      POSTGRES_USER: riskmesh
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - pgdata-ingestion:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riskmesh -d ingestion_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-scoring:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: scoring_db
      POSTGRES_USER: riskmesh
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-scoring:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riskmesh -d scoring_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-casemanagement:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: casemanagement_db
      POSTGRES_USER: riskmesh
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata-casemanagement:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riskmesh -d casemanagement_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-notification:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: riskmesh
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - pgdata-notification:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riskmesh -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9092:9092"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/dashboards:/etc/grafana/dashboards

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"

volumes:
  pgdata-ingestion:
  pgdata-scoring:
  pgdata-casemanagement:
  pgdata-notification: