spring:
  application:
    name: casemanagement-service
  datasource:
    url: jdbc:postgresql://localhost:5434/casemanagement_db
    username: riskmesh
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8083

management:
  server:
    port: 8093
  endpoints:
    web:
      exposure:
        include: health,info